apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: okak2006/query:latest
---
# Cluster IP: easy to use URL / Name to manage access to this pod
apiVersion: v1
kind: Service
metadata:
  # if you have multiple services for the same pod make sure a different name is given
  name: query-clusterip-srv
spec:
  # select which pod to expose
  selector:
    app: query
  type: ClusterIP
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
